import { compareGraphs, getDb, loadGraphFromSnapshot, SiteRepository, SnapshotRepository } from '@crawlith/core';
import type { Graph, PluginContext } from '@crawlith/core';
import type { SnapshotCompareRequest, SnapshotDiffFlags, SnapshotDiffOutputFormat } from './types.js';

/**
 * Encapsulates business logic for snapshot comparison and incremental baseline loading.
 */
export class SnapshotDiffService {
  /**
   * Parses and validates `--compare` payload as a pair of numeric snapshot IDs.
   * @param flags CLI flags available on plugin context.
   * @returns Parsed compare request or `null` when compare mode is disabled.
   */
  parseCompareRequest(flags: SnapshotDiffFlags): SnapshotCompareRequest | null {
    if (!flags.compare) return null;

    const rawValues = Array.isArray(flags.compare)
      ? flags.compare
      : [flags.compare];

    if (rawValues.length !== 2) {
      throw new Error('Error: --compare requires exactly two snapshot IDs (<oldSnapshotId> <newSnapshotId>).');
    }

    const [oldRaw, newRaw] = rawValues.map(String);
    const oldSnapshotId = Number.parseInt(oldRaw, 10);
    const newSnapshotId = Number.parseInt(newRaw, 10);

    if (!Number.isFinite(oldSnapshotId) || !Number.isFinite(newSnapshotId)) {
      throw new Error('Error: --compare only accepts numeric snapshot IDs.');
    }

    return { oldSnapshotId, newSnapshotId };
  }

  /**
   * Resolves output format from CLI flags.
   * @param flags CLI flags from plugin context.
   * @returns Selected output format.
   */
  parseOutputFormat(flags: SnapshotDiffFlags): SnapshotDiffOutputFormat {
    return flags.format === 'json' ? 'json' : 'pretty';
  }

  /**
   * Compares two persisted snapshots.
   * @param request Pair of snapshot IDs.
   * @returns Diff result generated by Crawlith core.
   */
  compareSnapshots(request: SnapshotCompareRequest) {
    const oldGraph = loadGraphFromSnapshot(request.oldSnapshotId);
    const newGraph = loadGraphFromSnapshot(request.newSnapshotId);
    return compareGraphs(oldGraph, newGraph);
  }

  /**
   * Resolves previous completed snapshot graph for incremental crawl mode.
   * @param targetUrl URL passed to crawl command.
   * @returns Previous graph when found, otherwise `null`.
   */
  resolvePreviousGraph(targetUrl: string): Graph | null {
    const db = getDb();
    const siteRepo = new SiteRepository(db);
    const snapshotRepo = new SnapshotRepository(db);

    const domain = new URL(targetUrl).hostname.replace('www.', '');
    const site = siteRepo.getSite(domain);
    if (!site) return null;

    const latestSnapshot = snapshotRepo.getLatestSnapshot(site.id, 'completed');
    if (!latestSnapshot) return null;

    return loadGraphFromSnapshot(latestSnapshot.id);
  }

  /**
   * Reads a valid target URL from context flags for incremental mode.
   * @param ctx Plugin context.
   * @returns Candidate URL or `null` when missing.
   */
  getTargetUrl(ctx: PluginContext): string | null {
    const flags = (ctx.flags || {}) as SnapshotDiffFlags;
    const fromFlags = typeof flags.url === 'string' ? flags.url : null;
    if (fromFlags && !fromFlags.startsWith('-')) return fromFlags;

    return typeof (ctx as PluginContext & { url?: unknown }).url === 'string'
      ? String((ctx as PluginContext & { url?: unknown }).url)
      : null;
  }
}
